# Generated by Django 6.0.3 on 2026-04-21 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga_api', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='genre',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
