# Generated by Django 6.0.3 on 2026-04-22 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga_api', '0004_cartitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('delivery', 'Delivery'), ('pickup', 'Pickup')], default='delivery', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='is_received',
            field=models.BooleanField(default=False),
        ),
    ]
